# Site settings
title: "Ashish Nitin Patil's personal website"
person_full_name: "Ashish Nitin Patil"
person_first_name: Ashish
person_last_name: Patil
person_nickname: "!mmorta!"
person_gender: male
email: "ashishnitinpatil@gmail.com"
description: "Pythonista | Engineer | DotA 2 fanatic"
cv: "Resume - Ashish Patil.pdf"
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: ashishnitinpatil.github.io # used to determine if google analytics should be triggered
url: https://ashishnitinpatil.github.io # the base hostname & protocol for your site
permalink: /:title/
exclude: [vendor] # avoid irritating errors

#vcard_url: url_here
instagram_username: ashishnitinpatil
facebook_username: ashishnitinpatil
twitter_username: shad0w_wa1k3r
github_username: ashishnitinpatil
stackoverflow:
  id: 2689986
  username: shad0w_wa1k3r
linkedin_username: ashishnitinpatil
dota_id: 129201469
imdb_id: ur33741705


# Build settings
markdown: kramdown
